source('R/functions/getParameters.R')
source('R/functions/getParameters_OM.R')
source('R/functions/Check_Identifiable_vs2.R')
#source('R/functions/getParms_noAge.R')
source('R/functions/load_data_seasons.R')
source('R/functions/run_agebased_model_true_Catch.R')
source('R/functions/plotUncertainty.R')
source('R/functions/getSelec.R')
source('R/functions/create_TMB_data.R')
#source('R/functions/getRefpoint_biomass.R')
source('R/functions/Check_Identifiable_vs2.R')
source('R/functions/getF.R')
source('R/functions/run_multiple_MSEs.R')
source('R/functions/getRefpoint.R')

